nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_headers: ["content-type", "Authorization", "origin", "accept"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "PATCH"]
        expose_headers: ["link"]
        max_age: 3600
        hosts: []
    paths:
        "^/": ~
